(cl:defpackage robot_control-srv
  (:use )
  (:export
   "ROBOTSERVOCONFIGURE"
   "<ROBOTSERVOCONFIGURE-REQUEST>"
   "ROBOTSERVOCONFIGURE-REQUEST"
   "<ROBOTSERVOCONFIGURE-RESPONSE>"
   "ROBOTSERVOCONFIGURE-RESPONSE"
  ))

