// Generated by gencpp from file robot_control/RobotServoConfigure.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURE_H
#define ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURE_H

#include <ros/service_traits.h>


#include <robot_control/RobotServoConfigureRequest.h>
#include <robot_control/RobotServoConfigureResponse.h>


namespace robot_control
{

struct RobotServoConfigure
{

typedef RobotServoConfigureRequest Request;
typedef RobotServoConfigureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotServoConfigure
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::RobotServoConfigure > {
  static const char* value()
  {
    return "0cd3ecf7339bcd1bc5e56bad74e9aa6e";
  }

  static const char* value(const ::robot_control::RobotServoConfigure&) { return value(); }
};

template<>
struct DataType< ::robot_control::RobotServoConfigure > {
  static const char* value()
  {
    return "robot_control/RobotServoConfigure";
  }

  static const char* value(const ::robot_control::RobotServoConfigure&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::RobotServoConfigureRequest> should match
// service_traits::MD5Sum< ::robot_control::RobotServoConfigure >
template<>
struct MD5Sum< ::robot_control::RobotServoConfigureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::RobotServoConfigure >::value();
  }
  static const char* value(const ::robot_control::RobotServoConfigureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::RobotServoConfigureRequest> should match
// service_traits::DataType< ::robot_control::RobotServoConfigure >
template<>
struct DataType< ::robot_control::RobotServoConfigureRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::RobotServoConfigure >::value();
  }
  static const char* value(const ::robot_control::RobotServoConfigureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::RobotServoConfigureResponse> should match
// service_traits::MD5Sum< ::robot_control::RobotServoConfigure >
template<>
struct MD5Sum< ::robot_control::RobotServoConfigureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::RobotServoConfigure >::value();
  }
  static const char* value(const ::robot_control::RobotServoConfigureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::RobotServoConfigureResponse> should match
// service_traits::DataType< ::robot_control::RobotServoConfigure >
template<>
struct DataType< ::robot_control::RobotServoConfigureResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::RobotServoConfigure >::value();
  }
  static const char* value(const ::robot_control::RobotServoConfigureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURE_H
