// Generated by gencpp from file robot_control/RobotServoConfigureResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURERESPONSE_H
#define ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct RobotServoConfigureResponse_
{
  typedef RobotServoConfigureResponse_<ContainerAllocator> Type;

  RobotServoConfigureResponse_()
    : sum(false)  {
    }
  RobotServoConfigureResponse_(const ContainerAllocator& _alloc)
    : sum(false)  {
  (void)_alloc;
    }



   typedef uint8_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RobotServoConfigureResponse_

typedef ::robot_control::RobotServoConfigureResponse_<std::allocator<void> > RobotServoConfigureResponse;

typedef boost::shared_ptr< ::robot_control::RobotServoConfigureResponse > RobotServoConfigureResponsePtr;
typedef boost::shared_ptr< ::robot_control::RobotServoConfigureResponse const> RobotServoConfigureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator1> & lhs, const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator1> & lhs, const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6878fbf450c7ecf53a60b908b6689ac";
  }

  static const char* value(const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6878fbf450c7ecfULL;
  static const uint64_t static_value2 = 0x53a60b908b6689acULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/RobotServoConfigureResponse";
  }

  static const char* value(const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sum\n"
;
  }

  static const char* value(const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotServoConfigureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::RobotServoConfigureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::RobotServoConfigureResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ROBOTSERVOCONFIGURERESPONSE_H
